title: "From HK to SG"
email: fromhktosg@gmail.com
timezone: UTC
baseurl: ''
# domain: "fromhktosg.github.io"
# url: "https://fromhktosg.github.io"
permalink: "/:title/"
# permalink: /:lang/:title/
# permalink: "/:lang/:categories/:year/:month/:day/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 30
locale: en_sg
# lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-MKV97NLQEL

# Social
social:
  instagram: https://www.instagram.com/fromhktosg/
  facebook: https://www.facebook.com/fromhktosg/
  twitter: https://twitter.com/fromhktosg

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
- jekyll-multiple-languages-plugin

languages: ["en", "zh"]
default_lang: "en"
exclude_from_localizations: ["javascript", "images", "css"]
# exclude_from_localizations: ["assets", "js", "images", "css"]